### ISSUE TITLE
Form issue during testing

### ISSUE THREAD

**Issue by romubaronvp** [Joffcom/n8n-nodes-form-trigger#10]
Hi team,

I've been using this custom node for few months and I've been really happy with it.

But following the 0.215.1 release, I'm no longer able to get the node running properly in test mode (using the Test URL).
The page is properly displayed I got a 404 error when submitting my form.

Unfortunately, I don't see anything in our logs on our main process.

Note that the icon is no longer present :cry: 

Let me know if you want me to run any test on it.

Thanks

**Comment by Joffcom** [comment]
Evening,

Can you try on 215.2, there was a bug with some trigger nodes not listening that has been resolved.

**Comment by romubaronvp** [comment]
Indeed, the issue is fixed!
Thanks a lot.

**Comment by Joffcom** [comment]
No problem, it is nice when issues fix themselves 🙂
